### ISSUE TITLE
can't find Wishbone stuff in the github RoaLogic/RV12 repo

### ISSUE THREAD

**Issue by frantony** [RoaLogic/RV12#13]
The top RV12 [README.md](https://github.com/RoaLogic/RV12/blob/v1.1-rc1/README.md#interfaces) file states that RV12 supports Wishbone interface.

I can't find any traces of Wishbone in RV12 version v1.1-rc1 (408e3357ecf5847f300af659191a7a079bc892f6).
Also there is no Wishbone mention in the 'External interfaces' section of RV12 documentation ([docs/tex/06-external-if.tex](https://github.com/RoaLogic/RV12/blob/v1.1-rc1/docs/tex/06-external-if.tex)).

**Comment by sphardy** [comment]
Hello Antony - Thanks for the feedback. Couple of data points for you:

1. Wishbone: The reference to Wishbone should not have been in the README. We have a verison of RV12 with Wishbone support under development but it is not yet complete and the README reference was an oversight that should not have been removed.

2. Please note that the commit you reference is not the latest release - there were a couple of minor updates after that RC was created. Latest is [here](https://github.com/RoaLogic/RV12/releases/latest)

3. Update coming: I have created a new branch with a correction to the README and also included your VIM swap file fix. You can find that [here](https://github.com/RoaLogic/RV12/tree/Dev/v1.2). We will check for other incorrect file inclusions and then release this version asap.

**Comment by sphardy** [comment]
[v1.2](https://github.com/RoaLogic/RV12/releases/tag/v1.2) is now released with the noted documentation update and removal of the unnecessary swap file. Wishbone support is a work in progress - we don't have an ETA for completion yet

As a consequence I will close this issue
