### ISSUE TITLE
Documents Update

### ISSUE THREAD

**Issue by riscveval** [RoaLogic/RV12#9]
Hi The Documents links are unable to open. So can you update Documents?  also also update the Makefile targets?

**Comment by rherveille** [comment]
1) The documentation is not yet in a state where we can release it. We are working on it. As soon as it's ready and reviewed we'll release it. We will add a note ...
2) What updates to the makefile targets would you like?

**Comment by riscveval** [comment]
How to run benchmarks and simulation ? also any FPGA design flow for RV12?

**Comment by rherveille** [comment]
To run the regression tests go to sim/ahb3lite/regression/run
Do "make SIM=<simulator>" to start the regression test, where simulator is one of msim, riviera, vcs, ncsim. For ModelSim, Riviera-PRO, VCS, and ncsim respectively.

**Comment by sphardy** [comment]
Hello @riscveval! I have been compiling documentation for all the Roa Logic IP including the RV12. A first draft for the other IP is now released in their Master branches. 

For RV12, we are close to release but still need to complete one chapter. If you would like to take a look at what we currently have you can find it in the "Documentation_Clean" branch - https://github.com/RoaLogic/RV12/tree/Documentation_Clean

PDF and markdown versions of the Datasheet are included in the branch. The README file provides links. The chapter we still need to complete is Chapter 3 - RV12 Execution Pipeline. 

If you could provide feedback that would be very helpful. Please open new issues for what you find.

**Comment by sphardy** [comment]
Documentation is now formally [released](https://github.com/RoaLogic/RV12/tree/v1.1)

Closing this issue
